version: "3"

volumes:
  database:
    driver: local

services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0.32
    container_name: ai_boilerplate_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ai_boilerplate
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - database:/var/lib/mysql